config/routes.rb
Rasslin::Application.routes.draw do
  resources :body_parts

  resources :move_types

  resources :positions

  resources :moves

  

end

app/controllers/move_types_controller.rb
class MoveTypesController < ApplicationController
  before_action :set_move_type, only: [:show, :edit, :update, :destroy]

  # GET /move_types
  # GET /move_types.json
  def index
    @move_types = MoveType.all
  end

  # GET /move_types/1
  # GET /move_types/1.json
  def show
  end

  # GET /move_types/new
  def new
    @move_type = MoveType.new
  end

  # GET /move_types/1/edit
  def edit
  end

  # POST /move_types
  # POST /move_types.json
  def create
    @move_type = MoveType.new(move_type_params)

    respond_to do |format|
      if @move_type.save
        format.html { redirect_to @move_type, notice: 'Move type was successfully created.' }
        format.json { render action: 'show', status: :created, location: @move_type }
      else
        format.html { render action: 'new' }
        format.json { render json: @move_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /move_types/1
  # PATCH/PUT /move_types/1.json
  def update
    respond_to do |format|
      if @move_type.update(move_type_params)
        format.html { redirect_to @move_type, notice: 'Move type was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @move_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /move_types/1
  # DELETE /move_types/1.json
  def destroy
    @move_type.destroy
    respond_to do |format|
      format.html { redirect_to move_types_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_move_type
      @move_type = MoveType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def move_type_params
      params.require(:move_type).permit(:name)
    end
end

app/helpers/move_types_helper.rb
module MoveTypesHelper
end

app/views/move_types/_form.html.erb
<%= form_for(@move_type) do |f| %>
  <% if @move_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@move_type.errors.count, "error") %> prohibited this move_type from being saved:</h2>

      <ul>
      <% @move_type.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/move_types/edit.html.erb
<h1>Editing move_type</h1>

<%= render 'form' %>

<%= link_to 'Show', @move_type %> |
<%= link_to 'Back', move_types_path %>

app/views/move_types/index.html.erb
<h1>Listing move_types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @move_types.each do |move_type| %>
      <tr>
        <td><%= move_type.name %></td>
        <td><%= link_to 'Show', move_type %></td>
        <td><%= link_to 'Edit', edit_move_type_path(move_type) %></td>
        <td><%= link_to 'Destroy', move_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Move type', new_move_type_path %>

app/views/move_types/new.html.erb
<h1>New move_type</h1>

<%= render 'form' %>

<%= link_to 'Back', move_types_path %>

app/views/move_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @move_type.name %>
</p>

<%= link_to 'Edit', edit_move_type_path(@move_type) %> |
<%= link_to 'Back', move_types_path %>