config/routes.rb
Rasslin::Application.routes.draw do
  resources :body_parts

  resources :move_types

  resources :positions

  resources :moves

  

end

app/models/move.rb
class Move < ActiveRecord::Base
  belongs_to :move_type, class_name: MoveType
  belongs_to :body_helper, class_name: BodyPart
  belongs_to :body_opp, class_name: BodyPart
  belongs_to :control_start_pos, class_name: Position
  belongs_to :opp_start_pos, class_name: Position
  belongs_to :control_success_pos, class_name: Position
  belongs_to :opp_success_pos, class_name: Position
  belongs_to :control_fail_pos, class_name: Position
  belongs_to :opp_fail_pos, class_name: Position
end

app/models/move_type.rb
class MoveType < ActiveRecord::Base
  has_many :moves, class_name: Move, foreign_key: :move_type_id
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  before_action :set_move, only: [:show, :edit, :update, :destroy]

  # GET /moves
  # GET /moves.json
  def index
    @moves = Move.all
  end

  # GET /moves/1
  # GET /moves/1.json
  def show
  end

  # GET /moves/new
  def new
    @move = Move.new
  end

  # GET /moves/1/edit
  def edit
  end

  # POST /moves
  # POST /moves.json
  def create
    @move = Move.new(move_params)

    respond_to do |format|
      if @move.save
        format.html { redirect_to @move, notice: 'Move was successfully created.' }
        format.json { render action: 'show', status: :created, location: @move }
      else
        format.html { render action: 'new' }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moves/1
  # PATCH/PUT /moves/1.json
  def update
    respond_to do |format|
      if @move.update(move_params)
        format.html { redirect_to @move, notice: 'Move was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moves/1
  # DELETE /moves/1.json
  def destroy
    @move.destroy
    respond_to do |format|
      format.html { redirect_to moves_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_move
      @move = Move.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def move_params
      params.require(:move).permit(:name, :agility, :strength, :technical, :risk, :brawling, :durability, :body_helper_id, :body_opp_id, :injure, :move_type_id, :control_start_pos_id, :opp_start_pos_id, :control_success_pos_id, :opp_success_pos_id, :control_fail_pos_id, :opp_fail_pos_id, :daze, :special)
    end
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/views/moves/_form.html.erb
<%= form_for(@move) do |f| %>
  <% if @move.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@move.errors.count, "error") %> prohibited this move from being saved:</h2>

      <ul>
      <% @move.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <fieldset>
    <legend>Attributes</legend>
    <div class="field floater" >
      <%= f.label :agility %><br>
      <%= f.text_field :agility %>
    </div>
    <div class="field floater">
      <%= f.label :strength %><br>
      <%= f.text_field :strength %>
    </div>
    <div class="field">
      <%= f.label :technical %><br>
      <%= f.text_field :technical %>
    </div>
    <div class="field floater">
      <%= f.label :risk %><br>
      <%= f.text_field :risk %>
    </div>
    <div class="field floater">
      <%= f.label :brawling %><br>
      <%= f.text_field :brawling %>
    </div>
    <div class="field">
      <%= f.label :durability %><br>
      <%= f.text_field :durability %>
    </div>
  </fieldset>
  <fieldset>
    <legend>Body Parts</legend>
    <div class="field floater" >
      <%= f.label :body_helper %><br>
      <%= f.collection_select :body_helper_id, BodyPart.order(:name), :id, :name, prompt: 'Choose one:' %>
    </div>
    <div class="field floater">
      <%= f.label :body_opp %><br>
      <%= f.collection_select :body_opp_id, BodyPart.order(:name), :id, :name, prompt: 'Choose one:' %>
    </div>
    <div class="field floater">
      <%= f.label :injure %><br>
      <%= f.text_field :injure %>
    </div>
  </fieldset>
  <div class="field">
    <%= f.label :move_type_id %><br>
    <%= f.collection_select :move_type_id, MoveType.order(:name), :id, :name, prompt: 'Choose one:' %>
  </div>
  <fieldset>
    <legend>Start Position</legend>
    <div class="field floater">
      <%= f.label 'Controller'%><br>
      <%= f.collection_select :control_start_pos_id, Position.order(:name), :id, :name, prompt: 'Choose one:' %>
    </div>
    <div class="field">
      <%= f.label 'Opponent' %><br>
      <%= f.collection_select :opp_start_pos_id, Position.order(:name), :id, :name, prompt: 'Choose one:' %>
    </div>
  </fieldset>
  <fieldset>
    <legend>Success</legend>
    <div class="field floater">
      <%= f.label 'Controller' %><br>
      <%= f.collection_select :control_success_pos_id, Position.order(:name), :id, :name, prompt: 'Choose one:' %>
    </div>
    </div>
    <div class="field">
      <%= f.label 'Opponent' %><br>
      <%= f.collection_select :opp_success_pos_id, Position.order(:name), :id, :name, prompt: 'Choose one:' %>
    </div>
  </fieldset>
  <fieldset>
    <legend>Failed</legend>
    <div class="field floater">
      <%= f.label 'Controller' %><br>
      <%= f.collection_select :control_fail_pos_id, Position.order(:name), :id, :name, prompt: 'Choose one:' %>
    </div>
    <div class="field">
      <%= f.label 'Opponent' %><br>
      <%= f.collection_select :opp_fail_pos_id, Position.order(:name), :id, :name, prompt: 'Choose one:' %>
    </div>
  <fieldset>
  <div class="field">
    <%= f.label :daze %><br>
    <%= f.text_field :daze %>
  </div>
  <div class="field">
    <%= f.label :special %><br>
    <%= f.text_area :special %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/moves/edit.html.erb
<h1>Editing move</h1>

<%= render 'form' %>

<%= link_to 'Show', @move %> |
<%= link_to 'Back', moves_path %>

app/views/moves/index.html.erb
<h1>Listing moves</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Agility</th>
      <th>Strength</th>
      <th>Technical</th>
      <th>Risk</th>
      <th>Brawling</th>
      <th>Durability</th>
      <th>Body helper</th>
      <th>Body opp</th>
      <th>Injure</th>
      <th>Move type</th>
      <th>Control start pos</th>
      <th>Opp start pos</th>
      <th>Control success pos</th>
      <th>Opp success pos</th>
      <th>Control fail pos</th>
      <th>Opp fail pos</th>
      <th>Daze</th>
      <th>Special</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @moves.each do |move| %>
      <tr class="<%= cycle('even', 'odd') %>">
        <td><%= move.name %></td>
        <td><%= move.agility %></td>
        <td><%= move.strength %></td>
        <td><%= move.technical %></td>
        <td><%= move.risk %></td>
        <td><%= move.brawling %></td>
        <td><%= move.durability %></td>
        <td><%= move.body_helper.name %></td>
        <td><%= move.body_opp.name %></td>
        <td><%= move.injure %></td>
        <td><%= move.move_type.name %></td>
        <td><%= move.control_start_pos.name %></td>
        <td><%= move.opp_start_pos.name %></td>
        <td><%= move.control_success_pos.name %></td>
        <td><%= move.opp_success_pos.name %></td>
        <td><%= move.control_fail_pos.name %></td>
        <td><%= move.opp_fail_pos.name %></td>
        <td><%= move.daze %></td>
        <td><%= move.special %></td>
        <td><%= link_to 'Show', move %></td>
        <td><%= link_to 'Edit', edit_move_path(move) %></td>
        <td><%= link_to 'Destroy', move, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Move', new_move_path %>

app/views/moves/new.html.erb
<h1>New move</h1>

<%= render 'form' %>

<%= link_to 'Back', moves_path %>

app/views/moves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @move.name %>
</p>

<p>
  <strong>Agility:</strong>
  <%= @move.agility %>
</p>

<p>
  <strong>Strength:</strong>
  <%= @move.strength %>
</p>

<p>
  <strong>Technical:</strong>
  <%= @move.technical %>
</p>

<p>
  <strong>Risk:</strong>
  <%= @move.risk %>
</p>

<p>
  <strong>Brawling:</strong>
  <%= @move.brawling %>
</p>

<p>
  <strong>Durability:</strong>
  <%= @move.durability %>
</p>

<p>
  <strong>Body helper:</strong>
  <%= @move.body_helper.name %>
</p>

<p>
  <strong>Body opp:</strong>
  <%= @move.body_opp.name %>
</p>

<p>
  <strong>Injure:</strong>
  <%= @move.injure %>
</p>

<p>
  <strong>Move type:</strong>
  <%= @move.move_type.name %>
</p>

<p>
  <strong>Control start pos:</strong>
  <%= @move.control_start_pos.name %>
</p>

<p>
  <strong>Opp start pos:</strong>
  <%= @move.opp_start_pos.name %>
</p>

<p>
  <strong>Control success pos:</strong>
  <%= @move.control_success_pos.name %>
</p>

<p>
  <strong>Opp success pos:</strong>
  <%= @move.opp_success_pos.name %>
</p>

<p>
  <strong>Control fail pos:</strong>
  <%= @move.control_fail_pos.name %>
</p>

<p>
  <strong>Opp fail pos:</strong>
  <%= @move.opp_fail_pos.name %>
</p>

<p>
  <strong>Daze:</strong>
  <%= @move.daze %>
</p>

<p>
  <strong>Special:</strong>
  <%= @move.special %>
</p>

<%= link_to 'Edit', edit_move_path(@move) %> |
<%= link_to 'Back', moves_path %>